# -*- coding: utf-8 -*-
"""bakhtawar-YOLO project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5j0zkASGfyw7FuSmjFfF31WHPh_Qr6g
"""

!pip install ultralytics

from ultralytics import YOLO
import cv2
from google.colab.patches import cv2_imshow

model = YOLO('yolov8n.pt')

results = model('/content/ssp0.1.jpg')

results[0].save("my_img_detector.jpg")

img = cv2.imread("my_img_detector.jpg")
cv2_imshow(img)
cv2.waitKey(0)
cv2.destroyAllWindows()